title: Elliot Ginger
description: Systems • Data • Automation
url: https://elliotginger.com

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

permalink: /:categories/:year/:month/:day/:title/

header_pages:
  - work.md
  - thinking.md
  - about.md
  - contact.md
